In [1]:
# 이 예제는 `2. RNN 실습 - 영화평 분류`

# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import SimpleRNN, Dense, Input, Embedding
# model = Sequential()
# model.add(Input(shape=(80,))) # 입력하는 영화평의 길이를 80으로 제한, 길면 자르고, 짧으면 zero padding
# model.add(Embedding(input_dim=10000, output_dim=32))
# model.add(SimpleRNN(64))
# model.add(Dense(2, activation='softmax')) # model.add(Dense(1, activation='sigmoid'))
# model.summary()

# 이 모델의 test set accuracy는 77%

In [2]:
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np

# MultiHeadAttention 레이어 정의
class MultiHeadAttention(layers.Layer):
    def __init__(self, num_heads, key_dim):
        # MultiHeadAttention 클래스 초기화 메소드
        super(MultiHeadAttention, self).__init__()
        self.num_heads = num_heads  # 헤드 수
        self.key_dim = key_dim  # 각 헤드의 차원
        self.depth = key_dim // num_heads  # 각 헤드의 깊이
        
        # Query, Key, Value를 생성하기 위한 밀집 레이어
        self.wq = layers.Dense(key_dim)
        self.wk = layers.Dense(key_dim)
        self.wv = layers.Dense(key_dim)
        
        # 마지막 출력 밀집 레이어
        self.dense = layers.Dense(key_dim)

    def split_heads(self, x, batch_size):
        # (batch_size, seq_len, key_dim) -> (batch_size, num_heads, seq_len, depth)로 변환
        x = tf.reshape(x, (batch_size, -1, self.num_heads, self.depth))
        # (batch_size, seq_len, num_heads, depth) -> (batch_size, num_heads, seq_len, depth)로 전치
        return tf.transpose(x, perm=[0, 2, 1, 3])

    def call(self, v, k, q):
        # 입력 시퀀스의 배치 크기
        batch_size = tf.shape(q)[0]
        
        # 입력 텐서를 Query, Key, Value로 변환
        q = self.wq(q)
        k = self.wk(k)
        v = self.wv(v)
        
        # 각 헤드로 분할
        q = self.split_heads(q, batch_size)
        k = self.split_heads(k, batch_size)
        v = self.split_heads(v, batch_size)
        
        # 스케일드 닷 프로덕트 어텐션 계산
        scaled_attention, attention_weights = self.scaled_dot_product_attention(q, k, v)
        
        # 각 헤드의 출력을 결합하여 원래의 형태로 변환
        scaled_attention = tf.transpose(scaled_attention, perm=[0, 2, 1, 3])
        concat_attention = tf.reshape(scaled_attention, (batch_size, -1, self.key_dim))
        
        # 마지막 밀집 레이어를 통과하여 최종 출력 생성
        output = self.dense(concat_attention)
        
        return output
    
    def scaled_dot_product_attention(self, q, k, v):
        # Query와 Key의 내적을 계산
        matmul_qk = tf.matmul(q, k, transpose_b=True)
        
        # 스케일링을 위해 Key의 차원으로 나눔
        dk = tf.cast(tf.shape(k)[-1], tf.float32)
        scaled_attention_logits = matmul_qk / tf.math.sqrt(dk)
        
        # 어텐션 가중치를 소프트맥스로 계산
        attention_weights = tf.nn.softmax(scaled_attention_logits, axis=-1)
        
        # 어텐션 가중치를 Value에 곱하여 최종 어텐션 출력 계산
        output = tf.matmul(attention_weights, v)
        
        return output, attention_weights


In [3]:
# Transformer를 이용한 영화평 분류

import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential, Model

inputs = layers.Input(shape=(80,))

input_embedding = layers.Embedding(input_dim=10000, output_dim=32)(inputs)
positions = tf.range(start=0, limit=80)
pos_encoding = layers.Embedding(input_dim=80, output_dim=32)(positions)
pos_enc_output = pos_encoding + input_embedding

# attention_output = layers.MultiHeadAttention(num_heads=2, key_dim=32)(pos_enc_output, pos_enc_output)
attention_output = MultiHeadAttention(num_heads=3, key_dim=32)(pos_enc_output, pos_enc_output, pos_enc_output)
x = layers.add([pos_enc_output, attention_output])
x = layers.BatchNormalization()(x)

ffnn = Sequential([layers.Dense(64, activation="relu"), 
                   layers.Dense(32, activation="relu")])(x)
x = layers.add([ffnn, x])
x = layers.BatchNormalization()(x)
x = layers.GlobalAveragePooling1D()(x)
x = layers.Dropout(0.1)(x)

x = layers.Dense(64, activation="relu")(x)
x = layers.Dropout(0.1)(x)

outputs = layers.Dense(2, activation="softmax")(x)
model = Model(inputs=inputs, outputs=outputs)

model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 80)]                 0         []                            
                                                                                                  
 embedding (Embedding)       (None, 80, 32)               320000    ['input_1[0][0]']             
                                                                                                  
 tf.__operators__.add (TFOp  (None, 80, 32)               0         ['embedding[0][0]']           
 Lambda)                                                                                          
                                                                                                  
 multi_head_attention (Mult  (None, None, 32)             4224      ['tf.__operators__.add[0][

In [4]:
# model.compile(loss='binary_crossentropy', optimizer='adam',
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam',
              metrics=['accuracy'])

In [5]:
from tensorflow.keras.datasets import imdb
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000)
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(25000,) (25000,) (25000,) (25000,)


In [6]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_train_pad = pad_sequences(X_train, maxlen=80, truncating='post', padding='post')
X_test_pad = pad_sequences(X_test, maxlen=80, truncating='post', padding='post')

In [7]:
%%time
model.fit(X_train_pad, y_train, epochs=10, batch_size=200)

Epoch 1/10
125/125 [==============================] - 16s 114ms/step - loss: 0.4967 - accuracy: 0.7482
Epoch 2/10
125/125 [==============================] - 14s 113ms/step - loss: 0.3211 - accuracy: 0.8660
Epoch 3/10
125/125 [==============================] - 14s 114ms/step - loss: 0.2627 - accuracy: 0.8914
Epoch 4/10
125/125 [==============================] - 14s 114ms/step - loss: 0.2116 - accuracy: 0.9096
Epoch 5/10
125/125 [==============================] - 14s 113ms/step - loss: 0.1668 - accuracy: 0.9262
Epoch 6/10
125/125 [==============================] - 15s 117ms/step - loss: 0.1272 - accuracy: 0.9470
Epoch 7/10
125/125 [==============================] - 14s 115ms/step - loss: 0.0936 - accuracy: 0.9632
Epoch 8/10
125/125 [==============================] - 15s 121ms/step - loss: 0.0670 - accuracy: 0.9771
Epoch 9/10
125/125 [==============================] - 15s 120ms/step - loss: 0.0610 - accuracy: 0.9783
Epoch 10/10
125/125 [==============================] - 15s 118ms/step - l

In [8]:
model.evaluate(X_test_pad, y_test)

782/782 [==============================] - 10s 12ms/step - loss: 2.0335 - accuracy: 0.7748


[2.033520221710205, 0.7748399972915649]

In [9]:
print(X_test_pad.shape)

(25000, 80)


In [10]:
import numpy as np
pred = model.predict(X_test_pad)
# pred = (pred > 0.5).astype(int)
pred = np.argmax(pred, axis=1)

782/782 [==============================] - 10s 12ms/step


In [11]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, pred))

[[9489 3011]
 [2618 9882]]


In [12]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.77484

In [13]:
# 옵티마이저를 sgd로 바꿔보세요. accuracy: 0.57784
# 전체 단어의 개수를 1000개로 바꿔보세요. accuracy:
# 영화평의 길이를 200개로 바꿔보세요. accuracy:
# pad_sequence의 truncating과 padding을 pre로 바꿔보세요. accuracy:

In [14]:
# 아래 택스트를 긍/부정 분류하세요.
text = "My God the actors who potrayed the VIP people cannot act. I cringed everytime they said a line. It felt like they were just reading them. Even the intonation was off. It was like when we were kids and had to read a play in class and we exagerated the intonation. Terrible, just awful."

In [15]:
word_index = imdb.get_word_index()
# print(word_index)
# {'fawn': 34701, 'tsukino': 52006, 'nunnery': 52007,

In [16]:
word_to_idx = {k:(v+3) for k,v in word_index.items()}
word_to_idx["<PAD>"] = 0
word_to_idx["<START>"] = 1
word_to_idx["<UNK>"] = 2  # unknown
word_to_idx["<UNUSED>"] = 3

In [17]:
input_text = text.lower().split()
print(input_text)

['my', 'god', 'the', 'actors', 'who', 'potrayed', 'the', 'vip', 'people', 'cannot', 'act.', 'i', 'cringed', 'everytime', 'they', 'said', 'a', 'line.', 'it', 'felt', 'like', 'they', 'were', 'just', 'reading', 'them.', 'even', 'the', 'intonation', 'was', 'off.', 'it', 'was', 'like', 'when', 'we', 'were', 'kids', 'and', 'had', 'to', 'read', 'a', 'play', 'in', 'class', 'and', 'we', 'exagerated', 'the', 'intonation.', 'terrible,', 'just', 'awful.']


In [18]:
# 단어를 숫자로 변환합니다. 
# word_to_idx에 없는 단어는 2(<UNK>)로 지정하며, 
# 인덱스가 10000보다 크면 3(<UNUSED>)로 지정합니다.
def encoding(review_text):
  encoded = []
  for word in review_text:
    try:
      idx = word_to_idx[word]
      if idx>10000:
        encoded.append(3)
      else:
        encoded.append(idx)
    except:
      encoded.append(2)
  return encoded

input_encoded = encoding(input_text)

In [19]:
np.array(input_encoded)[np.newaxis, :]

array([[ 61, 558,   4, 156,  37,   2,   4,   3,  84, 566,   2,  13,   3,
          3,  36, 301,   6,   2,  12, 421,  40,  36,  71,  43, 886,   2,
         60,   4,   3,  16,   2,  12,  16,  40,  54,  75,  71, 362,   5,
         69,   8, 332,   6, 297,  11, 707,   5,  75,   3,   4,   2,   2,
         43,   2]])

In [20]:
input_pad = pad_sequences(
    np.array(input_encoded)[np.newaxis, :],
    maxlen=80, truncating='post', padding='post')

In [21]:
model.predict(input_pad) # LSTM을 이용한 인공신경망 모형은 부정(0)으로 분류함

1/1 [==============================] - 0s 25ms/step


array([[0.95886034, 0.04113967]], dtype=float32)